Changed read command to raw mode for some situations

diff --git a/bin/qjira b/bin/qjira
--- a/bin/qjira
+++ b/bin/qjira
@@ -33,7 +33,7 @@ Error()
 # Works
 _JIRA_ISSUE_DETAILS=$(curl -s  -X POST -H     "Authorization: Basic ${AUTH_HEADER}" \
                                        -H     "Content-Type: application/json" \
-                                       --data '{"jql":"key = '${TICKET}'","fields":["id","description"]}}' "${JIRA_SEARCH_URL}")
+                                       --data '{"jql":"key = '${TICKET}'","fields":["id","description"]}}' "${JIRA_SEARCH_URL}" || echo "qjira:ERROR")
 # in Test
 #_JIRA_ISSUE_DETAILS=$(curl -s  -X GET -H     "Authorization: Basic ${AUTH_HEADER}" \
 #                                      -H     "Content-Type: application/json" \
@@ -45,6 +45,7 @@ _JIRA_ISSUE_DETAILS=$(curl -s  -X POST -H     "Authorization: Basic ${AUTH_HEADE
 #curl -D- -X GET -H "Authorization: Basic ${AUTH_HEADER}" -H "Content-Type: application/json" "${JIRA_SERVER}/rest/api/2/user?username=user"
 # Issue description
 echo ${TICKET}
+echo ${_JIRA_ISSUE_DETAILS} | grep -q "qjira:ERROR" && echo "Jira issue. Check Jira is running, username/password or ticket number" && exit 1
 echo ${_JIRA_ISSUE_DETAILS} | jshon -e issues   -a -e fields  -e description -u
 
 #   _ISSUE_DESCRIPTION=$(echo ${_JIRA_ISSUE_DETAILS} | ${PYTHON} -c '
diff --git a/functions/ScorchE_Rules b/functions/ScorchE_Rules
--- a/functions/ScorchE_Rules
+++ b/functions/ScorchE_Rules
@@ -27,7 +27,7 @@ fn_GetRequest()
     printf "\n help <plugin>    at any time for additional parameters\n\n"
     printf " Please enter the request below.\n To complete the request is use a fullstop on a newline:\n (To quit type CANCEL)\n\n"
     while [[ "${str_Line}" != "." ]] ; do
-      read -r str_Line
+      read -e -r str_Line
           str_ULine=$(echo ${str_Line} | tr [:lower:] [:upper:])
 ##      if echo "${str_Line}" | grep -qi ACTION ; then
 ##        (( int_GetCount+=1 ))
@@ -88,16 +88,22 @@ fn_ProcessRequest()
         fi
         fn_JobHeader "${file_Job}"
         Task "echo AUDIT:START:\${str_StartTime}"
+printf "${fn_Call}: "
+        ${fn_Call}
 
-        echo "$(${fn_LogDate}) Plugin:${str_Call}" >> "${dir_Log}"/$(basename "${file_Job}").log
-        eval "${fn_Call}"
-        if [[ $? -ne 0 ]] ; then
-          echo "$(${fn_LogDate}) Error in plugin" >> "${dir_Log}"/$(basename "${file_Job}").log
+        int_ReturnCode=${PIPESTATUS[0]}
+        # PIPESTATUS AND USE PIPE TEE
+        if [[ ${int_ReturnCode} -ne 0 ]] ; then
+          echo "exit 1" >> "${file_Job}"
+          echo "# Template Begin" >> "${file_Job}"
+          cat "${file_Request}" >> "${file_Job}"
+          echo "# Template End" >> "${file_Job}"
+          echo "$(${fn_LogDate}) Error in plugin. Task creation not complete" >> "${dir_Log}"/$(basename "${file_Job}").log
           mv "${file_Job}" "${dir_Failed}"/.
           fn_PressEnter
           exit 1
         fi
-
+echo " int_TaskCount=${int_TaskCount}" ; sleep 3
         fn_JobFooter "${file_Job}"
         echo "$(${fn_LogDate}) Created by:${str_User} Tasks[${int_TaskCount}]" >> "${dir_Log}"/$(basename "${file_Job}").log
         (( int_JobCount+=1 ))
diff --git a/functions/Scorch_JobHandler b/functions/Scorch_JobHandler
--- a/functions/Scorch_JobHandler
+++ b/functions/Scorch_JobHandler
@@ -39,6 +39,7 @@
 ## fn_CheckOwnJobs()
 ## fn_SetJobOwner()
 ## fn_CheckOwner()
+## fn_JobState()
 
 
 
@@ -310,7 +311,7 @@ fn_GetRequest()
     printf "\n help <plugin>    at any time for additional parameters\n\n"
     printf " Please enter the request below.\n To complete the request is use a fullstop on a newline:\n (To quit type CANCEL)\n\n"
     while [[ "${str_Line}" != "." ]] ; do
-      read -r str_Line
+      read -e -r str_Line
 	    str_ULine=$(echo ${str_Line} | tr [:lower:] [:upper:])
       if [[  ${str_ULine} =~ HELP ]] ; then
         typeset local str_Help=${str_Line#help }
@@ -367,9 +368,16 @@ fn_ProcessRequest()
         Task "echo AUDIT:START:\${str_StartTime}"
 
         echo "$(${fn_LogDate}) Plugin:${str_Call}" >> "${dir_Log}"/$(basename "${file_Job}").log
-        eval "${fn_Call}"
-        if [[ $? -ne 0 ]] ; then
-          echo "$(${fn_LogDate}) Error in plugin" >> "${dir_Log}"/$(basename "${file_Job}").log
+        echo ${fn_Call} #>> "${dir_Log}"/$(basename "${file_Job}").log
+        ${fn_Call}
+        int_ReturnCode=${PIPESTATUS[0]}
+        # PIPESTATUS AND USE PIPE TEE
+        if [[ ${int_ReturnCode} -ne 0 ]] ; then
+          echo "exit 1" >> "${file_Job}"
+          echo "# Template Begin" >> "${file_Job}"
+          cat "${file_Request}" >> "${file_Job}"
+          echo "# Template End" >> "${file_Job}"
+          echo "$(${fn_LogDate}) Error in plugin. Task creation not complete" >> "${dir_Log}"/$(basename "${file_Job}").log
           mv "${file_Job}" "${dir_Failed}"/.
           fn_PressEnter
           exit 1
@@ -615,7 +623,7 @@ breakTask()
 
 Manual()
 {
-  breakTask "\"$*\""
+  breakTask "$*"
 }
 
 GetVar()
@@ -851,3 +859,9 @@ fn_CheckOwner()
   fi
 }
 readonly -f fn_CheckOwner
+
+fn_JobState()
+{
+  local file_Job=${1}
+  basename $(dirname $(find ${dir_Job} -name ${file_Job} | grep -v "/active/"))
+}
diff --git a/scorch b/scorch
--- a/scorch
+++ b/scorch
@@ -92,10 +92,11 @@
 ## 1.28 180518    marc   Working with centos
 ## 1.28.1         marc   Minor format fix
 ## 1.29           marc
+## 1.30           marc   
 ## git config --global core.editor "'C:\Users\marc\Downloads\Sublime Text Build 3143 x64\sublime_text.exe' -multiInst -nosession"
 
 ## Determine the program name and the running directory
-typeset str_ProgramVersion="1.29"
+typeset str_ProgramVersion="1.30dev"
 typeset    str_ProgramName="$(basename "$0")"
 typeset            dir_Run="$(dirname "$0")"
 typeset           dir_Orig="$(pwd)/${dir_Run}"
@@ -271,7 +272,7 @@ typeset b_Install=
 typeset file_Template=
 typeset str_Action=
 typeset lst_GetVar=
-typeset b_Interactice=1
+typeset b_NonInteractive=
 typeset b_Sync=
 
 ## Check for argument list
@@ -284,14 +285,14 @@ if [ $# -ne 0 ] ; then
       -v          ) echo "${str_ProgramName}[${str_ProgramVersion}]" ; exit 0 ;;
 
       ## API Mode
-      -a          ) shift ; file_Template=$(mktemp) ; str_Action=$1 ; b_Interactice=0 ;;
+      -a          ) shift ; file_Template=$(mktemp) ; str_Action=$1 ; b_NonInteractive=1 ;;
       -o          ) shift ; [[ ! $lst_GetVar ]] && lst_GetVar=$1 || lst_GetVar="${lst_GetVar};$1" ;;
       -s          ) b_Start=1 ;;
       -sync       ) b_Sync=1 ;;
       -dispatcher ) b_Dispatcher=1 ;;
 
       ## Internal Mode
-      -file       ) shift ; file_Template="$1" ; b_Interactice=0 ;;
+      -file       ) shift ; file_Template="$1" ; b_NonInteractive=1 ;;
       -new        ) b_New=1 ;;
       -background ) b_Background=1 ;;
 
@@ -344,15 +345,32 @@ if [[ ${file_Template} ]] ; then
   if [[ ${b_Sync} ]] ; then
     b_Debug=1
     sleep 1
-echo "find -L ${dir_Starting} ${dir_Pending} ${dir_Queued} ${dir_Running} -name $(basename ${file_Job}) )"
-    while [[ "$(find -L ${dir_Starting} ${dir_Pending} ${dir_Queued} -name $(basename ${file_Job}) )" ]] ; do
-      fn_RunJobs
+
+    while : ; do
+      str_JobState=$(fn_JobState $(basename ${file_Job}))
+      case $str_JobState in
+        new      ) echo "You must use -s to also start sync jobs" ; exit 1 ;;
+        
+        queued   ) echo "Checking dispatcher" ; fn_CheckDispatcher  ; sleep 5 ; fn_RunJobs ;;
+        starting ) echo "Running Own Jobs" ; sleep 5 ; fn_RunJobs ;;
+        queued | pending | running ) : ;;
+        
+        failed ) echo "$(basename ${file_Job}) FAILED" ; exit 1 ;;
+        completed ) echo "$(basename ${file_Job}) Completed" ; exit 0 ;;
+        *   ) echo "What is ${str_JobState}" ; exit 1 ;;
+      esac
       sleep 10
     done
+
+#    while [[ "$(find -L ${dir_Starting} ${dir_Pending} ${dir_Queued} -name $(basename ${file_Job}) )" ]] ; do
+#   fn_RunJobs
+#      sleep 10
+#    done
 
 echo "Now find the jobs final resting place - completed or failed or lost"
 find -L ${dir_Completed} -name $(basename ${file_Job}) && echo "SUCCESS" && exit 0
 find -L ${dir_Failed} -name $(basename ${file_Job}) && echo "FAILED" && exit 1
+
 echo "waiting for ${str_JobName} to complete"
 set | grep SAFE
 echo call scorch in background and exit clean
