1.20 Python showJobs

diff --git a/functions/Scorch_JobHandler b/functions/Scorch_JobHandler
--- a/functions/Scorch_JobHandler
+++ b/functions/Scorch_JobHandler
@@ -80,6 +80,7 @@ dir_Job="${dir_Job}"
 dir_Running="${dir_Running}"
 dir_Failed="${dir_Failed}"
 dir_Completed="${dir_Completed}"
+dir_Manual="${dir_Manual}"
 dir_Starting="${dir_Starting}"
 dir_Pause="${dir_Active}"
 dir_Active="${dir_Active}"
@@ -266,7 +267,7 @@ fn_ProcessRequest()
   typeset local int_JobCount=1
   typeset local int_FileCount=1
 
-  fn_GetJobID
+  int_JobID=$(fn_GetJobID)
   # Multi Action is enterprise feature
   ls ${dir_Tmp}/${str_ProgramName}.$$.*
   for str_EachFile in ${dir_Tmp}/${str_ProgramName}.$$.* ; do
@@ -275,7 +276,7 @@ fn_ProcessRequest()
     echo "${str_EachFile}"
 	
     fn_ExtractPairs
-    #b_Debug=1
+    b_Debug=1
     [[ "${b_Debug}" ]] && echo "Action List: ${ACTION_LIST}"
     for ACTION in ${ACTION_LIST} ; do
 	    #echo "$ACTION is"
@@ -329,7 +330,23 @@ fn_GetJobID()
   
   typeset local file_JobIDLock="${file_JobID}".lock
 
-  if ( set -o noclobber; > "${file_JobIDLock}") 2> /dev/null ; then
+#  if ( set -o noclobber; > "${file_JobIDLock}") 2> /dev/null ; then
+#    if [ -r "${file_JobID}" ] ; then
+#      int_JobID=$(cat "${file_JobID}")
+#    else
+#      int_JobID=0
+#    fi
+#    (( int_JobID+=1 ))
+#    echo ${int_JobID} > "${file_JobID}"
+#    rm -f "${file_JobIDLock}"
+#  else
+#    echo "Could not get exclusive lock"
+#    exit 1
+#  fi
+
+  (
+    flock -w 1 200
+    #cat $file_JobID
     if [ -r "${file_JobID}" ] ; then
       int_JobID=$(cat "${file_JobID}")
     else
@@ -337,11 +354,8 @@ fn_GetJobID()
     fi
     (( int_JobID+=1 ))
     echo ${int_JobID} > "${file_JobID}"
-    rm -f "${file_JobIDLock}"
-  else
-    echo "Could not get exclusive lock"
-    exit 1
-  fi
+    echo ${int_JobID}
+  ) 200> "${file_JobIDLock}"
 }
 readonly -f fn_GetJobID
 
@@ -350,10 +364,10 @@ fn_ExtractPairs()
   GetVar -pattern "From"    -name FROM
   GetVar -pattern "Sent"    -name SENT
   GetVar -pattern "Action"  -name ACTION_LIST
-  GetVar -pattern "Release" -name RELEASE                -default "NO-REL"
-  GetVar -pattern "Enviro"  -name ENVIRONMENT_LIST -list -default "NO-ENV"
+  GetVar -pattern "Release" -name RELEASE                -default ""
+  GetVar -pattern "Enviro"  -name ENVIRONMENT_LIST -list -default "NA"
   GetVar -pattern "Type"    -name TYPE                   -default ""
-  GetVar -pattern "Ticket"  -name TICKET                 -default ""  
+  GetVar -pattern "Ticket"  -name TICKET                 -default "ID-${int_JobID}"  
 }
 ## Enterprise feature available readonly -f fn_ExtractPairs
 
@@ -453,7 +467,7 @@ pauseTask()
 {
   ## Expection to the naming convention is pauseTask. This is used in plugins by users
   int_Sleep=${1:-10}
-  Task "printf \"Sleeping for ${int_Sleep} seconds\" ; sleep ${int_Sleep}" 
+  Task "printf \"Sleeping for ${int_Sleep} seconds\n\" ; sleep ${int_Sleep}" 
 }
 
 breakTask()
@@ -488,8 +502,9 @@ GetVar()
   typeset local str_Default=
   typeset local b_IgnoreCase=1
   typeset local b_List=
-## typeset local b_Upper=
-  
+  typeset local b_Upper=
+  typeset local b_Lower=
+ 
   if [ $# -ne 0 ] ; then
     while [ $# -gt 0 ] ; do
       case "${1}" in
@@ -498,7 +513,8 @@ GetVar()
         -default ) shift ; str_Default="${1}" ;;
         -c       )         b_IgnoreCase=0     ;;
         -list    )         b_List=1           ;;
-##		-upper   )         b_Upper=1          ;;
+        -upper   )         b_Upper=1          ;;
+        -lower   )         b_Lower=1          ;;
       esac
       shift
     done
@@ -527,7 +543,8 @@ GetVar()
   ## If a value hasnt been found or is empty, use the default if one is set
   ## ======================================================================
   [[ "${str_Value}" ]] || str_Value=${str_Default}
-##  [[ "${b_Upper}" ]] && str_Value=$(echo ${str_Value} | tr [:lower:] [:upper:])
+  [[ "${b_Upper}"   ]] && str_Value=${str_Value^^}
+  [[ "${b_Lower}"   ]] && str_Value=${str_Value,,}
 ##         tmp=${1:1}               # Strip off leading '/' . . .
 ##          str_Name=${tmp%%:*}     # Extract name.
 ##          str_Value=${tmp##*:}         # Extract value.
@@ -546,7 +563,8 @@ NGetVar()
   typeset local str_Default=
   typeset local b_IgnoreCase=1
   typeset local b_List=
-##  typeset local b_Upper=" -i "
+  typeset local b_Upper=
+  typeset local b_Lower=
   
   if [ $# -ne 0 ] ; then
     while [ $# -gt 0 ] ; do
@@ -556,7 +574,8 @@ NGetVar()
         -default ) shift ; str_Default="${1}" ;;
         -c       )         b_IgnoreCase=0     ;;
         -list    )         b_List=1           ;;
-##		-upper   )         b_Upper=           ;;
+        -upper   )         b_Upper=1          ;;
+        -lower   )         b_Lower=1          ;;
       esac
       shift
     done
@@ -567,6 +586,9 @@ NGetVar()
   echo "TMP is <${_tmp}>"
   Nstr_Name=${_tmp%%:*}
   Nstr_Value=${_tmp##*:}
+  [[ "${b_Upper}"   ]] && Nstr_Value=${Nstr_Value^^}
+  [[ "${b_Lower}"   ]] && Nstr_Value=${Nstr_Value,,}
+
   echo ${Nstr_Name}"=\"${Nstr_Value}\""
   sleep 5
 }
@@ -583,13 +605,13 @@ fn_Transition()
   case ${str_Transition} in
 
     ## Jobs requiring the dispatcher
-    queue   ) fn_ShowJobs2 failed fixing superseded new      ; str_Target="${dir_Queued}" ; fn_CheckDispatcher ;;
-    resume  ) fn_ShowJobs2 failed fixing superseded          ; str_Target="${dir_Queued}" ; fn_CheckDispatcher ;;
+    queue   ) fn_ShowJobs failed fixing superseded new      ; str_Target="${dir_Queued}" ; fn_CheckDispatcher ;;
+    resume  ) fn_ShowJobs failed fixing superseded          ; str_Target="${dir_Queued}" ; fn_CheckDispatcher ;;
 
     ## Jobs not requiring the dispatcher
-    delete  ) fn_ShowJobs2 failed fixing superseded new      ; str_Target="${dir_Deleted}" ;;
-    unqueue ) fn_ShowJobs2 failed superseded starting queued ; str_Target="${dir_New}"     ;;
-    pause   ) fn_ShowJobs2 running starting queued pending   ; str_Target="${dir_Active}" ;;
+    delete  ) fn_ShowJobs failed fixing superseded new      ; str_Target="${dir_Deleted}" ;;
+    unqueue ) fn_ShowJobs failed superseded starting queued ; str_Target="${dir_New}"     ;;
+    pause   ) fn_ShowJobs running starting queued pending   ; str_Target="${dir_Active}" ;;
 
   esac
 
@@ -604,16 +626,16 @@ fn_Transition()
   arr_Answer=$(fn_Range "${str_Answer}")
   if [ "${arr_Answer}" != "x " ] ; then
     for int_Choice in ${arr_Answer} ; do
-	  if [[ ${int_Choice} -le 0 ]] || [[ ${int_Choice} -ge ${int_Count} ]] ; then
+	    if [[ ${int_Choice} -le 0 ]] || [[ ${int_Choice} -ge ${int_Count} ]] ; then
         printf "Out of range" 
         fn_PressEnter
         return 0
       fi
-      
+
       typeset local  file_Link="${dir_Job}"/${arr_States[${int_Choice}]}/${arr_Jobs[${int_Choice}]}
       typeset local   file_Job="${dir_Active}/${arr_Jobs[${int_Choice}]}"
       typeset local   file_Log="${dir_Log}/$(basename "${file_Job}")".log
-	  typeset local file_Rules="${dir_Active}/$(basename "${file_Link}")".rules
+      typeset local file_Rules="${dir_Active}/$(basename "${file_Link}")".rules
 
       fn_Audit "${file_Job}" "$(basename "${str_Target}")"
       case ${str_Transition} in
@@ -656,9 +678,9 @@ fn_CheckOwnJobs()
 {
   if [ "$(find "${dir_Starting}/." "${dir_Queued}/." "${dir_Pending}/." -name "${str_JobPrefix}*" -exec grep -l ^str_Owner="${str_Owner}" {} \; )" ] ; then
     printf "\n\n%s\n" "You have queued jobs that have not yet been started."
-	read -n 1 -p "Do you want to run a version in background to complete them? [y/n] " char_Answer
-	printf "\n\n"
-	[[ "${char_Answer}" = "y" ]] || [[ "${char_Answer}" = "Y" ]] && nohup "${dir_Base}"/${str_ProgramName} -background -j ${dir_Job} </dev/null >> "${file_ProgLog}" &
+    read -n 1 -p "Do you want to run a version in background to complete them? [y/n] " char_Answer
+    printf "\n\n"
+    [[ "${char_Answer}" = "y" ]] || [[ "${char_Answer}" = "Y" ]] && nohup "${dir_Base}"/${str_ProgramName} -background -j ${dir_Job} </dev/null >> "${file_ProgLog}" &
   fi
 }
 readonly -f fn_CheckOwnJobs
@@ -667,7 +689,7 @@ fn_SetJobOwner()
 {
   typeset local file_Job="${1}"
   if grep "^str_Owner=" "${file_Job}" ; then
-	fn_Audit "${file_Job}" "accepted ownership of the job"
+    fn_Audit "${file_Job}" "accepted ownership of the job"
     sed 's/^str_Owner=.*/str_Owner='${str_User}'/g' "${file_Job}" > "${file_Job}".tmp
 	mv "${file_Job}".tmp "${file_Job}"
   fi
diff --git a/functions/Scorch_Manager b/functions/Scorch_Manager
--- a/functions/Scorch_Manager
+++ b/functions/Scorch_Manager
@@ -26,15 +26,14 @@ fn_Manager()
   hex_MD5=$(md5sum ${dir_Base}/${str_ProgramName} | cut -d" " -f1)
   while : ; do
     fn_ShowTop
-    fn_ShowJobs2 superseded failed fixing new running starting pending queued completed
+    fn_ShowJobs superseded failed fixing new running starting pending queued completed
     fn_ShowLine "="
     fn_DisplayMOTD
     printf "\n${dis_Reset}"
-	fn_ContextMenu
+    fn_ContextMenu
 
 
-
-    read -t ${int_Refresh} char_Choice
+    read -n 1 -t ${int_Refresh} char_Choice
 
     case ${char_Choice} in
       ## Create a new job
@@ -53,16 +52,36 @@ fn_Manager()
       ## Misc
       m | M ) fn_EditMOTD           ;;
       t | T ) fn_ShowTasks          ;;
-      [0-9]* ) fn_AdminFunctions ${char_Choice} ;;
+      l | L ) fn_LockManager        ;;
+      x | X ) break ;;
+
 
       ## Releases
-      open       ) fnE_MkOpenScorch ;;
-      enterprise ) fnE_MkEscorchtar ;;
+      [0-9] ) fn_CatchWord ${char_Choice} "number" ;;
 
-      l | L ) fn_LockManager        ;;
-      set )   fnE_Set ;;
-      x | X ) break ;;
-     * ) fn_SetLayout ;;
+      o | O ) 
+         read -t ${int_Refresh} char_ChoiceExtra
+         str_Choice="${char_Choice,,}${char_ChoiceExtra,,}"
+         case ${str_Choice} in
+            open       ) fnE_MkOpenScorch ;;
+         esac  ;;
+
+      e | E )
+         read -t ${int_Refresh} char_ChoiceExtra
+         str_Choice="${char_Choice,,}${char_ChoiceExtra,,}"
+         case ${str_Choice} in
+            enterprise ) fnE_MkEscorchtar ;;
+         esac  ;;
+
+      s | S )
+         read -t ${int_Refresh} char_ChoiceExtra
+         str_Choice="${char_Choice,,}${char_ChoiceExtra,,}"
+         case ${str_Choice} in
+            set )   fnE_Set ;;
+         esac  ;;
+
+
+      * ) fn_SetLayout ;;
 
     esac
 	fn_RunJobs
@@ -79,10 +98,10 @@ fn_ViewJob()
   ${cmd_Editor} "${file_View}"
   if ! diff "${file_Orig}" "${file_View}" ; then
     printf "\n\nWarning. Not in edit mode. Changes will not be saved.\n"
-	read -n 1 -p "Do you want to save your changes to /tmp? [y/n] " char_Answer
-	printf "\n\n"
-	if [[ "${char_Answer}" = "y" ]] || [[ "${char_Answer}" = "Y" ]] ; then
-	  mv "${file_View}" /tmp/$(basename "${file_Orig}")
+	  read -n 1 -p "Do you want to save your changes to /tmp? [y/n] " char_Answer
+	  printf "\n\n"
+	  if [[ "${char_Answer}" = "y" ]] || [[ "${char_Answer}" = "Y" ]] ; then
+	    mv "${file_View}" /tmp/$(basename "${file_Orig}")
       fn_Audit "${file_Orig}" "saved an edited copy of job and saved a copy in /tmp"
     fi
 	#fn_PressEnter
@@ -100,11 +119,41 @@ fn_EditJob()
   ${cmd_Editor} "${file_Edit}"
   if ! diff "${file_Orig}" "${file_Edit}" ; then
 	  mv "${file_Edit}" "${file_Orig}"
-      fn_Audit "${file_Orig}" "edited job"
+    fn_Audit "${file_Orig}" "edited job"
   fi
   [ -f "${file_Edit}" ] && rm -f "${file_Edit}"
 }
 readonly -f fn_EditJob
+
+fn_Cancel()
+{
+  typeset local    file_Link="$1"
+  typeset local str_JobState="$2"
+  typeset local     file_Log="${dir_Log}/$(basename ${file_Link})".log
+
+  fn_CheckOwner "${file_Link}"
+  if [[ "${str_JobState}" = "running" ]] ; then
+    echo kill job
+    ps -fu ${str_User} | grep $(basename ${file_Link}) | grep -v bash | grep -v grep
+    int_PID=$(ps -fu ${str_User} | grep $(basename ${file_Link}) | grep -v grep | awk -F" " '{print $2}')
+    ps -fu ${str_User}
+    pstree -p ${int_PID}
+    echo ${int_PID} 
+    printf "\n\n Killing Process with PID[${int_PID}]"
+    # mv ${file_Link} ${dir_Failed}
+
+   # kill ${int_PID}
+    fn_PressEnter
+  elif  [[ "${str_JobState}" = "failed"  ]] ; then
+    fn_Audit "${file_Link}" "Cancelled at task:$(fn_GetResumePoint ${file_Log} ) "
+    mv ${file_Link} ${dir_Completed}
+    printf "\n\n Cancelled Job : ${file_Link}"
+    fn_PressEnter
+  else
+    echo "Incorrect call"
+  fi
+  sleep 2
+}
 
 fn_AdminFunctions()
 {
@@ -122,12 +171,16 @@ fn_AdminFunctions()
       fn_JobInfo
       type fnE_RulesMenu >/dev/null 2>&1 && fnE_RulesMenu
       fn_ContextMenu ${str_JobState}
-      read -t 30 char_Choice
+      read -n 1 -t 30 char_Choice
 
       case ${char_Choice} in
 	
+        # 
+        ## Abort Failed or Running jobs
+        c | C ) fn_Cancel "${file_Link}" "${str_JobState}" ;;
+
         ## View CSV
-        c | C ) ${cmd_Editor} "${file_CSV}" ;;
+        #c | C ) ${cmd_Editor} "${file_CSV}" ;;
 
         ## Edit job
         v | V ) fn_ViewJob "${file_ActiveJob}" ;;
@@ -194,7 +247,6 @@ fn_AdminFunctions()
                 return 0 ;;
 
         ## Task View
-        t | T ) fn_ShowTasks "${file_Job}"          ;;
 
         ## Mark Job as Fix in Progress (FIP)
         f | F ) echo " "
@@ -207,8 +259,7 @@ fn_AdminFunctions()
 
         ## Amend Job rules
         a | A ) fnE_AmendRules        ;;
-		tail  ) trap "return 0" 2 ; tail -f "${file_Log}" ;;
-
+        t     ) fn_CatchWord ${char_Choice} "tail tasks" ;;
         x | X ) return 0 ;;
         *     ) return 0 ;;
       esac
@@ -220,3 +271,30 @@ fn_AdminFunctions()
   fn_SetLayout
 }
 readonly -f fn_AdminFunctions
+
+fn_CatchWord()
+{
+  local char_ChoiceExtra="$1"
+  local arr_WordList="$2"
+  local int_Length=1
+  local str_Word=${char_ChoiceExtra}
+  local int_Del=1
+  while  [ "${char_ChoiceExtra}" != "" ]  ; do
+    read -n 1 -t 30 char_ChoiceExtra
+    if [ "${char_ChoiceExtra}" = "" ] ; then
+      int_Length=${#str_Word} 
+      int_Del=$(( int_Length - 1 )) 
+      (( int_Del >= 0 )) && eval str_Word=\${str_Word:0:${int_Del}} && printf "\b \b\b \b" || ( printf "\b \b" && continue )
+    else
+      str_Word=${str_Word}${char_ChoiceExtra}
+    fi
+  done
+  # To be extended
+  case ${str_Word} in
+    t | T      ) fn_ShowTasks "${file_Job}"          ;;
+    tail       ) trap "return 0" 2 ; tail -f "${file_Log}" ;;
+    [0-9]*     ) fn_AdminFunctions ${str_Word}  ;;
+    *          ) clear ;;
+  esac
+  #echo "${str_Word}"
+}
