Work in progress

diff --git a/functions/Scorch_JobHandler b/functions/Scorch_JobHandler
--- a/functions/Scorch_JobHandler
+++ b/functions/Scorch_JobHandler
@@ -30,10 +30,11 @@ fn_JobHeader()
   # The file to be created is passed as a variable
 
   typeset local file_Job=${1}
-  echo "Creating ${dir_New}/${file_Job}"
-  touch "${dir_New}"/${file_Job}
+  echo "Creating ${file_Job}"
+  touch "${file_Job}"
+  fn_CreateFile "${file_Job}"
 
-  cat > "${dir_New}"/${file_Job} << EOF
+  cat > "${file_Job}" << EOF
 #!/bin/bash
 
     #####  ####  ####  #####   #### #    #
@@ -52,9 +53,11 @@ str_StartTime="\$(date +%s)"
 str_Owner=$(whoami)
 
 # Job settings
+int_JobID=${int_JobID}
 int_ResumePoint=
 int_Last=0
 str_JobName="\$(basename \$0)"
+
 
 # Directory locations
 dir_Job="${dir_Job}"
@@ -97,8 +100,8 @@ fn_JobFooter()
   # The file to be appended to is passed as a variable
 
   typeset local file_Job=${1}
-  echo "Adding footer to ${dir_New}/${file_Job}"
-  cat >> "${dir_New}"/${file_Job} << EOF
+  echo "Adding footer to ${file_Job}"
+  cat >> "${file_Job}" << EOF
 
 int_StartTask=\${int_Resume:-1}
 #int_Last=${int_Task}
@@ -123,15 +126,14 @@ fn_NewJob()
   fn_GetRequest
   fn_ProcessRequest
 
-  echo "Header"
-  fn_JobHeader ${str_JobPrefix}file
-  echo "Add Tasks"
-  echo "Footer"
-  fn_JobFooter ${str_JobPrefix}file
-  echo "# Template Used" >> "${dir_New}"/${str_JobPrefix}file
-  cat "${file_Request}" >> "${dir_New}"/${str_JobPrefix}file
+
+
+
+
+  echo "# Template Used" >> "${file_Job}"
+  cat "${file_Request}" >> "${file_Job}"
   rm "${file_Request}"
-  chmod 754 "${dir_New}"/${str_JobPrefix}file
+  chmod 754 "${file_Job}"
   sleep 2
 
 }
@@ -164,12 +166,23 @@ fn_GetRequest()
 
 fn_ProcessRequest()
 {
+  typeset local int_JobCount=1
   echo "stub:fn_ProcessRequest"
   fn_GetJobID
   fn_ExtractPairs
-echo "$ACTION:$RELEASE:$ENVIRONMENT:$TYPE:$TICKET"
-  sleep 5
+  
+  echo "Action: ${ACTION}"
+  for str_EachACTION in ${ACTION} ; do
+    file_Job="${dir_New}"/${str_JobPrefix}${TICKET}_${int_JobID}.${int_JobCount}_${SYSTEM}_${ENVIRONMENT}_${str_EachACTION}_${RELEASE}
+    fn_JobHeader "${file_Job}"
 
+    Task "date +$s ; echo PID:\$$"
+
+    echo "Add Tasks"
+    fn_JobFooter "${file_Job}"
+    (( int_JobCount+=1 ))
+  done
+  fn_PressEnter
 }
 
 fn_CheckDispatcher()
@@ -181,13 +194,32 @@ fn_CheckDispatcher()
 fn_GetJobID()
 {
   echo "stub: ${FUNCNAME}"
+  file_JobID="${dir_Var}"/JobID
+  [[ ! -f "${file_JobID}" ]] && echo "BROKEN" && fn_CreateFile "${file_JobID}"
+  
+  typeset local file_JobIDLock="${file_JobID}".lock
+
+  if ( set -o noclobber; > "${file_JobIDLock}") 2> /dev/null ; then
+    if [ -r "${file_JobID}" ] ; then
+      int_JobID=$(cat "${file_JobID}")
+    else
+      int_JobID=0
+    fi
+    (( int_JobID+=1 ))
+    echo ${int_JobID} > "${file_JobID}"
+    rm -f "${file_JobIDLock}"
+  else
+    echo "Could not get exclusive lock"
+    exit 1
+  fi
+  
 }
 
 fn_ExtractPairs()
 {
   echo "stub: ${FUNCNAME}"
   GetVar -pattern "System"  -name SYSTEM             -default "NO-SYS"
-  GetVar -pattern "Action"  -name ACTION
+  GetVar -pattern "Action"  -name ACTION      -list
   GetVar -pattern "Release" -name RELEASE            -default "NO-REL"
   GetVar -pattern "Enviro"  -name ENVIRONMENT -list  -deafult "NO-ENV"
   GetVar -pattern "Type"    -name TYPE               -default ""
@@ -204,6 +236,7 @@ Task()
   str_Task1=${1}
   str_OR=${2:-}
   str_Task2=${2}
+  echo "${str_Task1}" >> "${file_Job}"
 
 }
 
diff --git a/functions/Scorch_SetUp b/functions/Scorch_SetUp
--- a/functions/Scorch_SetUp
+++ b/functions/Scorch_SetUp
@@ -112,3 +112,21 @@ fn_Range()
     fi
   done
 }
+
+fn_CreateFile()
+{
+  echo ""
+  typeset local file_Name="${1}"
+  typeset local b_Blank="${2:""}"
+  touch "${file_Name}" 
+  [[ $? -ne 0 ]] && echo "Error: Cannot create file ${file_Name}" && exit 1
+  chmod 664 "${file_Name}"
+  [[ "${b_Blank}" ]] && > "${file_Name}"
+
+}
+
+fn_PressEnter()
+{
+  printf "\n\n"
+  read -p " Press Enter to continue "
+}
