New OR Task and ActiveJob directory for live job

diff --git a/functions/Scorch_JobHandler b/functions/Scorch_JobHandler
--- a/functions/Scorch_JobHandler
+++ b/functions/Scorch_JobHandler
@@ -35,6 +35,7 @@ fn_JobHeader()
   typeset local file_Job=${1}
   echo "Creating ${file_Job}"
   #touch "${file_Job}"
+  ln -s ${dir_Active}/$(basename ${file_Job}) ${file_Job}
   fn_CreateFile "${file_Job}" blank
   cat > "${file_Job}" << EOF
 #!/bin/bash
@@ -83,7 +84,7 @@ fn_CheckTask()
   if [ \${int_RC} -ne 0 ] ; then
     mv "\${dir_Running}"/\${str_JobName} "\${dir_Failed}"/.
     echo "+\$(date "+%D %T") Failed:\${int_Task}" >> "\${dir_Failed}"/\${str_JobName}
-    echo "FAILD:\$(date "+%D %T"):Resume point:\${int_Task}" >> "\${file_Log}"
+    echo "FAILED:\$(date "+%D %T"):Resume point:\${int_Task}" >> "\${file_Log}"
     rm "\${LOCK}"
     exit 1
   else
@@ -137,10 +138,10 @@ echo "INFO:FINISH:\$(date "+%s")" >> "\${file_Log}"
 echo "\$(date "+%D %T") Tasks[\${int_Last}] Failures[\${int_FailureCount}]" >> "\${file_Log}"
 # CSV File
 # Request time,Response time, Start time, End Time, Job name, number of failures, who
- int_Responded=\$(grep -m 1 "INFO:RESPONSED" \${file_Log} | cut -d: -f3)
+ int_Responded=\$(grep -m 1 "INFO:RESPONDED" \${file_Log} | cut -d: -f3)
  str_Requested=${FROM:-${int_Responded}}
- int_Start=\$(grep -m 1 "INFO:START" \${file_Log} | cut -d: -f3)
- int_Finish=\$(grep -m 1 "INFO:FINISH"  \${file_Log} | cut -d: -f3) 
+ int_Start=\$(grep "INFO:START" \${file_Log} | tail -1 | cut -d: -f3)
+ int_Finish=\$(grep "INFO:FINISH"  \${file_Log} | tail -1 | cut -d: -f3) 
  (( int_Duration = int_Finish - int_Start ))
  echo \${str_Requested},\${int_Responded},\${int_Start},\${int_Finish},\${str_JobName},\${int_Duration} seconds,\${int_FailureCount},\${str_Owner} >> "\${dir_Completed}"/\${str_JobName}
 exit 0
@@ -151,7 +152,6 @@ EOF
   cat "${file_Request}" >> "${file_Job}"
   echo "=============================" >> "${file_Job}"
   chmod 754 "${file_Job}"
-
 }
 readonly -f fn_JobFooter
 
@@ -289,15 +289,16 @@ Task()
   # This function will Add Tasks to a scorch Job
   # ================================================================================
   int_TaskCount=${int_TaskCount:-0}
-  str_Task1=${1}
-  str_OR=${2:-}
-  str_Task2=${2}
+  typeset local str_Task1=${1}
+  typeset local str_OR=${2}
+  typeset local str_Task2=${3}
+  typeset local str_AltTask2=
 
-#  printf "fn_Task_${int_TaskCount}()\n{\n  ${str_Task1}\t>> \"\${file_Log}\" 2>&1 \t#${str_ProgramName}_Task\n  fn_CheckTask \$? \${int_StartTask}\n}\n\n" >> "${file_Job}"
-  printf "fn_Task_${int_TaskCount}(){ ${str_Task1}\t>> \"\${file_Log}\" 2>&1 ; fn_CheckTask \$? \${int_StartTask};}\t#${str_ProgramName}_Task\n" >> "${file_Job}"
+  [[ "${str_OR}" = "OR" ]] && [[ "${str_Task2}" != "" ]] && str_AltTask="|| ${str_Task2} >> \"\${file_Log}\" 2>&1" >> ${file_Job}
+  printf "fn_Task_${int_TaskCount}(){ ${str_Task1}\t>> \"\${file_Log}\" 2>&1 ${str_AltTask} ; fn_CheckTask \$? \${int_StartTask};}\t#${str_ProgramName}_Task\n" >> "${file_Job}"
 
   (( int_TaskCount+=1 ))
-
+  str_OR=""
 }
 readonly -f Task
 
