Tracking recent changes

diff --git a/functions/Scorch_JobHandler b/functions/Scorch_JobHandler
--- a/functions/Scorch_JobHandler
+++ b/functions/Scorch_JobHandler
@@ -61,12 +61,12 @@ fn_JobHeader()
 # #####  ####  ####  #    #  #### #    #
 
 # Created: $(date)
-# By: $(whoami)
+# By: ${str_User}
 # Using: ${str_ProgramName}[${str_ProgramVersion}]
 
 # Audit
 str_StartTime="\$(date +%s)"
-str_Owner=$(whoami)
+str_Owner=${str_User}
 
 # Job settings
 int_JobID=${int_JobID}
@@ -117,8 +117,8 @@ fn_CheckTask()
       mv "\${dir_Running}"/\${str_JobName} "\${dir_Failed}"/.
       rm "\${dir_Pause}"/\${str_JobName}".pause"
       (( int_Task+=1 ))
-      echo "\$(${fn_LogDate}) Paused. Resume point:\${int_Task}" >> "\${dir_Failed}"/\${str_JobName}
-      echo "\$(${fn_LogDate}) Paused. Resume point:\${int_Task}" >> "\${file_Log}"
+      echo "\$(${fn_LogDate}) Paused. Resume point automatically set for resume:\${int_Task}" >> "\${dir_Failed}"/\${str_JobName}
+      echo "\$(${fn_LogDate}) Paused. Resume point automatically set for resume:\${int_Task}" >> "\${file_Log}"
       rm "\${LOCK}" 2>/dev/null
       exit 1
 	fi
@@ -144,7 +144,6 @@ fn_JobFooter()
 int_StartTask=\${int_ResumePoint:-1}
 int_Last=${int_TaskCount}
 
-#while [ \${int_StartTask} -le \${int_Last} ] ; do
 while (( int_StartTask <= int_Last )) ; do
   echo "===================" >> "\${file_Log}"
   echo "\$(${fn_LogDate}) Starting task [\${int_StartTask}/\${int_Last}]" >> "\${file_Log}"
@@ -193,7 +192,6 @@ fn_NewJob()
   fn_ShowTop
   fn_ShowLine "-"
   fn_LoadFunctions "${dir_Plugins}" "SP_"
-
   fn_GetRequest "${file_Template}"
   fn_GetRequestor
   fn_GetSent
@@ -226,10 +224,6 @@ fn_GetRequest()
     while [[ "${str_Line}" != "." ]] ; do
       read -r str_Line
 	  str_ULine=$(echo ${str_Line} | tr [:lower:] [:upper:])
-	  
-	  
-	  
-	  
       if [[  ${str_ULine} =~ HELP ]] ; then
         typeset local str_Help=${str_Line#help }
         if [[ "${str_Line}" ]] ; then
@@ -256,15 +250,18 @@ fn_ProcessRequest()
 
   fn_GetJobID
   # Multi Action is enterprise feature
+  ls ${dir_Tmp}/${str_ProgramName}.$$.*
   for str_EachFile in ${dir_Tmp}/${str_ProgramName}.$$.* ; do
     [[ -e ${str_EachFile} ]] || break
     file_Request=${dir_Tmp}/${str_ProgramName}.$$.${int_FileCount}
     echo "${str_EachFile}"
 	
     fn_ExtractPairs
-  
-    [[ "${b_Debug}" ]] && echo "Action: ${ACTION}"
+    #b_Debug=1
+    [[ "${b_Debug}" ]] && echo "Action List: ${ACTION_LIST}"
     for ACTION in ${ACTION_LIST} ; do
+	echo "$ACTION is"
+	
       for ENVIRONMENT in ${ENVIRONMENT_LIST} ; do
 
         int_TaskCount=0
@@ -291,7 +288,7 @@ fn_ProcessRequest()
         fi
 
         fn_JobFooter "${file_Job}"
-        echo "$(${fn_LogDate}) Created by:$(whoami) Tasks[${int_TaskCount}]" >> "${dir_Log}"/$(basename "${file_Job}").log
+        echo "$(${fn_LogDate}) Created by:${str_User} Tasks[${int_TaskCount}]" >> "${dir_Log}"/$(basename "${file_Job}").log
         (( int_JobCount+=1 ))
 
         if [[ $(ls "${dir_Failed}"/"${str_JobPrefix}*_${ACTION}_${ENVIRONMENT}*" 2>/dev/null)  ]] ; then
@@ -403,7 +400,7 @@ Task()
   typeset local   str_Task2=${3}
   typeset local str_AltTask=
 
-  [[ "${str_OR}" = "OR" ]] && [[ "${str_Task2}" != "" ]] && str_AltTask="|| ${str_Task2} >> \"\${file_Log}\" 2>&1" >> "${file_Job}"
+  [[ "${str_OR}" = "OR" ]] && [[ "${str_Task2}" != "" ]] && str_AltTask="|| ( ${str_Task2} ) >> \"\${file_Log}\" 2>&1" >> "${file_Job}"
   ##[[ "${b_StartGroup}" ]] && (( int_SubTask++ )) && str_SubTask=".${int_SubTask}" 
 
  if [[ "${b_Background}" ]] ; then
@@ -444,7 +441,7 @@ pauseTask()
 breakTask()
 {
   ## Exception to the naming convention is breakTask. This is used in plugins by users to force an exit
-  Task "printf \"Forcing interrupt. Skip this task to continue.  \" ; [ 0 = 1 ]" 
+  Task "printf \"$*\\nForcing interrupt. Skip this task to continue.  \" ; [ 0 = 1 ]" 
 }
 
 GetVar()
@@ -494,14 +491,14 @@ GetVar()
   if [ "${b_List}" ] ; then
     ## Lists can be passed as a space, comma or ampersand separated list 
 	## i.e. KEYWORD : ENV1, ENV2 ENV3 & ENV4
-    str_Value="$(awk 'BEGIN {
+    str_Value="$(${cmd_AWK} 'BEGIN {
        FS=":"
        IGNORECASE='"$b_IgnoreCase"' }
        $1 ~ /^ *'"$str_Pattern"'/ {print $2}'       "${file_Request}" | sed -e 's/[,&]/ /g' )"
   else
     ## If the item is not a list, get rid of any spaces and tabs with gsub
 	## ===================================================================
-    str_Value="$(awk 'BEGIN {
+    str_Value="$(${cmd_AWK} 'BEGIN {
        FS=":"
        IGNORECASE='"$b_IgnoreCase"' }
        $1 ~ /^ *'"$str_Pattern"'/ {gsub (/[ \t]+/, "");
@@ -574,7 +571,7 @@ fn_Transition()
     ## Jobs not requiring the dispatcher
     delete  ) fn_ShowJobs2 failed fixing superseded new      ; str_Target="${dir_Deleted}" ;;
     unqueue ) fn_ShowJobs2 failed superseded starting queued ; str_Target="${dir_New}"     ;;
-    pause   ) fn_ShowJobs2 running starting queued           ; str_Target="${dir_Active}" ;;
+    pause   ) fn_ShowJobs2 running starting queued pending   ; str_Target="${dir_Active}" ;;
 
   esac
 
@@ -613,7 +610,7 @@ fn_Transition()
         unqueue ) fn_CheckOwner "${file_Job}"
                   mv "${file_Link}" "${str_Target}"/. ;;
         delete  ) fn_CheckOwner "${file_Job}"
-                  echo ",,,$(date +%s),$(basename ${file_Job}),,,-1,$(whoami)" >> "${file_CSV}"
+                  echo ",,,$(date +%s),$(basename ${file_Job}),,,-1,${str_User}" >> "${file_CSV}"
                   mv "${file_Link}" "${str_Target}"/. ;;
         resume  ) fn_CheckOwner "${file_Job}"
                   fn_LogWhy
@@ -652,9 +649,8 @@ fn_SetJobOwner()
 {
   typeset local file_Job="${1}"
   if grep "^str_Owner=" "${file_Job}" ; then
-    echo "Work in progress"
 	fn_Audit "${file_Job}" "accepted ownership of the job"
-    sed 's/^str_Owner=.*/str_Owner='$(whoami)'/g' "${file_Job}" > "${file_Job}".tmp
+    sed 's/^str_Owner=.*/str_Owner='${str_User}'/g' "${file_Job}" > "${file_Job}".tmp
 	mv "${file_Job}".tmp "${file_Job}"
   fi
 }
@@ -663,10 +659,9 @@ readonly -f fn_SetJobOwner
 fn_CheckOwner()
 {
   typeset local file_Job="${1}"
-  if ! grep "^str_Owner=$(whoami)" "${file_Job}" ; then
-    printf "\n\nYou do not own this job\n\nCurrent owner:"
-    ## grep "^str_Owner=" "${file_Job}"
-    read -p "Do you wish to take ownership? [y/n]"
+  if ! grep "^str_Owner=${str_User}" "${file_Job}" ; then
+    printf "\n\nYou do not own this job\n\nCurrent owner: $(grep "^str_Owner=" "${file_Job}")\n\n"
+    read -n 1 -p "Do you wish to take ownership? [y/n]: "
     case $REPLY in
       y | Y ) fn_SetJobOwner "${file_Job}" ;;
 	  * ) break ;;
diff --git a/scorch b/scorch
--- a/scorch
+++ b/scorch
@@ -196,7 +196,7 @@ fn_LoadFunctions()
   typeset local  str_EachFile=
   ##[[ ${b_Display} ]] || printf "\nLoading %s\n" "${dir_Directory}"
   if [ -d "${dir_Directory}" ] ; then
-    SAVEIFS=$IFS
+	SAVEIFS=$IFS
     IFS=$(echo -en "\n\b")
     arr_Functions=$(find -L "${dir_Directory}" -name "${str_Search}*" | sed 's/ /\\ /g')
     arr_Functions=$(find -L "${dir_Directory}" -name "${str_Search}*")
@@ -206,7 +206,7 @@ fn_LoadFunctions()
 
         # Bash the function file for errors before loading it
         bash "${str_EachFile}" && . "${str_EachFile}"
-        if [[ $? = 0 ]] ; then
+		if [[ $? = 0 ]] ; then
           [[ ${b_Display} ]] || printf "%10s\n" "OK"
         else
           printf "%10s\n" "ERROR" && b_Errors=1
@@ -215,10 +215,10 @@ fn_LoadFunctions()
         echo "Cannot access <${str_EachFile}>"
       fi
     done
-    IFS=$SAVEIFS
+	IFS=$SAVEIFS
   else
     :
-    ##echo "$(pwd) ${dir_Directory} could not be found"
+	##echo "$(pwd) ${dir_Directory} could not be found"
   fi
 
   [[ "${b_Errors}" -eq 1 ]] && echo "Check function files for errors like missing quotes, brackets or malformed syntax" && exit 1
@@ -291,7 +291,7 @@ if [[ "${b_Background}" ]] ; then
   echo "$(${fn_LogDate}) ${str_User} Running in background to complete queued jobs"
   while [[ "$(find ${dir_Starting} ${dir_Pending} ${dir_Queued} -type l -exec grep -l "str_Owner=${str_User}" {} \;)" ]] ; do 
     fn_RunJobs
-    sleep 60
+	sleep 60
   done
   fn_RunJobs # one more try just to mop up
 else
