Tasks

diff --git a/functions/ScorchE_Rules b/functions/ScorchE_Rules
--- a/functions/ScorchE_Rules
+++ b/functions/ScorchE_Rules
@@ -73,6 +73,10 @@ fn_ProcessRequest()
 
     #[[ "${b_Debug}" ]] && echo "Action: ${ACTION}"
     for ACTION in ${ACTION_LIST} ; do
+
+
+echo "Last ${ACTION} took $(fn_DisplayTime $(scorchdb -f ${file_CSV} -starttime -endtime -failure "\.${ACTION}\." | tail -1))"
+
       for ENVIRONMENT in ${ENVIRONMENT_LIST} ; do
 
         int_TaskCount=0
@@ -98,9 +102,11 @@ fn_ProcessRequest()
         fn_JobHeader "${file_Job}"
         Task "echo AUDIT:START:\${str_StartTime}"
 #printf "${fn_Call}: "
+set +u 
         ${fn_Call}
 
         int_ReturnCode=${PIPESTATUS[0]}
+set -u
         # PIPESTATUS AND USE PIPE TEE
         if [[ ${int_ReturnCode} -ne 0 ]] ; then
           echo "exit 1" >> "${file_Job}"
@@ -110,7 +116,7 @@ fn_ProcessRequest()
           echo "$(${fn_LogDate}) Error in plugin. Task creation not complete" >> "${dir_Log}"/$(basename "${file_Job}").log
           mv "${file_Job}" "${dir_Failed}"/.
           fn_PressEnter
-          exit 1
+          return 1
         fi
         echo " $((int_TaskCount - 1)) tasks created"
 #        fn_JobFooter "${file_Job}"
@@ -187,13 +193,15 @@ fnE_AmendRules()
   printf " ${dis_ULOn}A${dis_ULOff}dd parent | ${dis_ULOn}D${dis_ULOff}elete rules  | e${dis_ULOn}X${dis_ULOff}it : "
 
   read ${str_Quick} -t 60 char_Choice
-
+  set +e
   case ${char_Choice} in
 
-          a | A ) fn_ShowJobs2 manual failed running starting pending queued new
-               fn_ShowLine
-               fn_GetAnswer
-               echo "PARENT:${arr_Jobs[${str_Answer}]}" >> ${file_ActiveJob}.rules ;;
+          a | A ) fn_ShowJobs manual failed running starting pending queued new
+                  #fn_ShowJobs2 manual failed running starting pending queued new
+                  fn_ShowLine
+                  fn_GetAnswer
+                  [[ "$str_Answer" == "x" ]] || [[ "${str_Answer}" == "" ]] && return 0
+                  echo "PARENT:${arr_Jobs[${str_Answer}]}" >> ${file_ActiveJob}.rules ;;
 
           d | D ) rm ${file_ActiveJob}.rules 2>/dev/null
                   # if link to active job in pending mv job to queued
@@ -203,6 +211,7 @@ fnE_AmendRules()
           x | X ) return 0 ;;
           *     ) return 0 ;;
   esac
+  set -e
 
 }
 readonly -f fnE_AmendRules
@@ -252,7 +261,7 @@ fn_CheckAuth()
       exit 1
     fi
   fi
-
+  set +e
   grep "^${str_User}:" ${file_Users}
   str_Authority=$(grep "^${str_User}:" ${file_Users} | cut -d":" -f2 | tr [:lower:] [:upper:])
   case ${str_Authority} in
@@ -261,5 +270,6 @@ fn_CheckAuth()
     F | FULL  )                  str_Authority="Normal"     ;;
     *         ) printf "\n${str_Authority}: Authority Level not set correctly.\nCheck with the ${str_ProgramName} administrator.\n" ; exit 1 ;;
   esac
+  set -e
 }
 readonly -f fn_CheckAuth
diff --git a/scorch b/scorch
--- a/scorch
+++ b/scorch
@@ -190,16 +190,26 @@
 ##                       #126 SetPrefs not required when non-interactive
 ##                       #127 Adding strict mode
 ##                       #129 Adding timeout feature
+## 2.8.2          marc   #132 Allow access to "log" from task list
+## 2.8.3 191127   marc   #133 Fix abrupt exit with no users file
+## 2.8.4 191128   marc   #12  Some estimated run time work
+## 2.8.5 191203   marc   Improved rules
+## 2.8.6 191213   marc   Adding Path updates for customer
+## 2.8.7 191220   marc   shellcheck lintifying
+## 2.8.8 200109   marc   #137 Fix failing exits from plugins
+## 2.8.9 200116   marc   #136 Fixed fail from exit tasks
+# shellcheck disable=SC2034
+# shellcheck source=/dev/null
 ## Determine the program name and the running directory
-set -uo pipefail     # -e is not used as that is how plugins are loaded (or not loaded)
+set -uo pipefail     # -e is not used yet as that is how plugins are loaded (or not loaded)
 IFS=$' \n\t'
 
-typeset str_ProgramVersion="2.8.1"
+typeset str_ProgramVersion="2.8.9"
 typeset       str_Codename="Balaur"
 typeset  str_LatestVersion="check"
 typeset    str_ProgramName="$(basename "$0")"
 typeset            dir_Run="$(dirname "$0")"
-typeset           dir_Orig="$(cd $dir_Run && pwd)"
+typeset           dir_Orig="$(cd "$dir_Run" && pwd)"
 typeset     fn_FullLogDate="date +${str_ProgramName}:%y%m%d-%H%M%S"
 typeset         fn_LogDate="date +%y%m%d-%H%M%S"
 typeset           str_User=$(whoami)
@@ -259,6 +269,8 @@ readonly -f fn_Help
 ## The running directory will become the str_BaseDir and will be dependant on a relative or absolute path
 typeset        dir_Base=$(fn_BaseDir "${dir_Run}")
 typeset          str_OS=$(uname -o)
+typeset      dir_Scorch="${dir_Base}"
+typeset            PATH=${PATH}:${dir_Base}:${dir_Base}/bin
 
 ## Directory definitions
 ## =====================
@@ -270,16 +282,16 @@ typeset         dir_Tmp="${dir_Base}/tmp/"
 
 ## Memory tmp files for multi scorch use systems
 if [ -w /dev/shm ] ; then
-  typeset      dir_Memory=/dev/shm/$(echo ${dir_Base} | cksum | tr ' ' '_')
+  typeset      dir_Memory=/dev/shm/$(echo "${dir_Base}" | cksum | tr ' ' '_')
 else
-  typeset      dir_Memory=${dir_|tmp}/no_shm
+  typeset      dir_Memory=${dir_Tmp}/no_shm
 fi
-mkdir -p  ${dir_Memory} 2>/dev/null
-chmod 775 ${dir_Memory} 2>/dev/null
+mkdir -p  "${dir_Memory}" 2>/dev/null
+chmod 775 "${dir_Memory}" 2>/dev/null
 
 if [[ ! -L ${dir_Base}/tmp/memory ]] ; then
   if [[ -w ${dir_Tmp} ]] ; then
-    ln -s ${dir_Memory} ${dir_Tmp}/memory
+    ln -s "${dir_Memory}" "${dir_Tmp}"/memory
     typeset         dir_Tmp=${dir_Base}/tmp/memory/
   fi
 fi
@@ -308,6 +320,8 @@ typeset    dir_Archived="${dir_Job}/archived"
 typeset     dir_Pending="${dir_Job}/pending"
 typeset      dir_Active="${dir_Job}/active"
 typeset      dir_Manual="${dir_Job}/manual"
+typeset        file_Job=""
+typeset     str_JobName=""
 
 typeset       str_Filter=""
 
@@ -342,6 +356,9 @@ typeset   int_ScreenWidth=80
 typeset           COLUMNS=80
 
 
+typeset         str_Log=log
+typeset  dir_LogBase="${dir_Var}/${str_ProgramName}/${str_Log}/"
+typeset dir_LogSpace="${dir_LogBase}/$(date +%Y%m)"
 
 fn_ResetJobDefinitions()
 {
@@ -419,8 +436,9 @@ fn_LoadFunctions()
         [[ ${b_NonInteractive} ]] || printf "%15s" "${str_EachFile#${dir_Directory}/*${str_Search}}"
 
         # Bash the function file for errors before loading it
-        bash -n "${str_EachFile}" && . "${str_EachFile}"
-        if [[ $? = 0 ]] ; then
+        #bash -n "${str_EachFile}" && source "${str_EachFile}"
+        if bash -n "${str_EachFile}" ; then
+          source "${str_EachFile}"
           [[ ${b_NonInteractive} ]] || printf "%10s\n" "OK"
         else
           printf "%10s\n" "ERROR" && b_Errors=1
@@ -436,8 +454,8 @@ fn_LoadFunctions()
         ##echo "$(pwd) ${dir_Directory} could not be found"
   fi
 
-  [[ ${b_Errors} -ge 1 ]] && echo HERE && exit 1 || :
-
+  [[ ${b_Errors} -ge 1 ]] && echo HERE && exit 1
+  :
 }
 readonly -f fn_LoadFunctions
 
@@ -460,10 +478,10 @@ typeset lst_GetVar=
 typeset b_NonInteractive=
 typeset b_Sync=
 
-[[ ${BASH_VERSION%%.*} -lt 4 ]] && printf "$str_ProgramName uses associative arrays which require bash 4. Your version: $BASH_VERSION\n" && exit 1
+[[ ${BASH_VERSION%%.*} -lt 4 ]] && printf "%s uses associative arrays which require bash 4. Your version: $BASH_VERSION\n" "$str_ProgramName" && exit 1
 
 # Checks for python
- ${dir_Python}/showJobs.py -n 1 new > /dev/null 2>&1 && str_ShowJobs=python || str_ShowJobs=bash
+"${dir_Python}/showJobs.py" -n 1 new > /dev/null 2>&1 && str_ShowJobs=python || str_ShowJobs=bash
 
 ## Check for argument list
 ## scorch can be run in several modes (install, new, file, dispatcher, manager and background)
@@ -507,9 +525,13 @@ fi
 fn_LoadFunctions "${dir_Functions}" "Scorch_" ${b_New}
 set -e
 ## As sson as function is defined, use it to set tmp 
-fn_Mkdir ${dir_Memory}
+fn_Mkdir "${dir_Memory}"
+fn_Mkdir "${dir_LogSpace}"
 
-echo $(fn_CheckLicense) && ENTERPRISE=1
+
+#echo "$(fn_CheckLicense)" &&
+ENTERPRISE=1
+
 if [[ ! -z $ENTERPRISE ]] ; then
   fn_LoadFunctions "${dir_Functions}" "ScorchE_"
   str_License="Enterprise"
@@ -537,14 +559,14 @@ if [[ ${str_Action} ]] ; then
 fi
 
 if [[ ${file_Template} ]] ; then
-  [[ ! -r "${file_Template}" ]] &&  echo "Error: Cannot read template file ${file_Request}" && exit 1
+  [[ ! -r "${file_Template}" ]] &&  echo "Error: Cannot read template file ${file_Template}" && exit 1
   fn_NewJob "${file_Template}"
   if [[ ${b_Sync} ]] ; then
     b_Debug=1
     sleep 1
 
     while : ; do
-      str_JobState=$(fn_JobState $(basename ${file_Job}))
+      str_JobState=$(fn_JobState "$(basename "${file_Job}")")
       case $str_JobState in
         new       ) echo "You must use -s (--start) to start sync jobs" ; exit 1 ;;
         
@@ -561,8 +583,8 @@ if [[ ${file_Template} ]] ; then
     done
 
     echo "Now find the jobs final resting place - completed or failed or lost"
-    find -L ${dir_Completed} -name $(basename ${file_Job}) && echo "SUCCESS" && exit 0
-    find -L ${dir_Failed} -name $(basename ${file_Job}) && echo "FAILED" && exit 1
+    find -L "${dir_Completed}" -name "$(basename ${file_Job})" && echo "SUCCESS" && exit 0
+    find -L "${dir_Failed}" -name "$(basename ${file_Job})" && echo "FAILED" && exit 1
 
     echo "waiting for ${str_JobName} to complete"
     set | grep SAFE
@@ -588,7 +610,7 @@ if [[ "${b_BackgroundRun}" ]] ; then
   # ADD LOOP HERE FOR JOB CHECKS
   typeset local b_Finished=1
   echo "$(${fn_LogDate}) ${str_User} Running in background to complete queued jobs"
-  while [[ "$(find ${dir_Starting} ${dir_Pending} ${dir_Queued} -type l -exec grep -l "str_Owner=${str_User}" {} \;)" ]] ; do
+  while [[ "$(find "${dir_Starting}" "${dir_Pending}" "${dir_Queued}" -type l -exec grep -l "str_Owner=${str_User}" {} \;)" ]] ; do
     fn_RunJobs
     sleep 60
   done
