#45 - associative array to track TASK status

diff --git a/functions/Scorch_JobHandler b/functions/Scorch_JobHandler
--- a/functions/Scorch_JobHandler
+++ b/functions/Scorch_JobHandler
@@ -78,7 +78,6 @@ int_Last=0
 str_JobName="\$(basename "\$0")"
 lst_PID=""
 
-
 # Directory locations
 dir_Job="${dir_Job}"
 dir_Running="${dir_Running}"
@@ -89,6 +88,7 @@ dir_Starting="${dir_Starting}"
 dir_Pause="${dir_Active}"
 dir_Active="${dir_Active}"
 file_Log="${dir_Var}/log/\${str_JobName}.log"
+file_Job="\${dir_Active}"/\${str_JobName}
 LOCK="${file_JobLock}.${ACTION}_${ENVIRONMENT}"
 echo "AUDIT:PID:\$\$" >> "\${file_Log}" 
 [[ ! -f "\${dir_Starting}"/\${str_JobName} ]] && echo "This is a ${str_ProgramName} script. Do not run these scripts manually unless you know what you are doing." && exit 1
@@ -97,7 +97,6 @@ echo "AUDIT:PID:\$\$" >> "\${file_Log}"
 
 [[ -w "\${dir_Starting}"/\${str_JobName} ]] && mv "\${dir_Starting}"/\${str_JobName} "\${dir_Running}"/.
 
-# Check Tasks
 fn_CheckTask()
 {
   typeset local int_RC=\${1}
@@ -106,34 +105,21 @@ fn_CheckTask()
   if [ \${int_RC} -ne 0 ] ; then
     if [ \${int_RC} = 99 ] ; then
       mv "\${dir_Running}"/\${str_JobName} "\${dir_Failed}"/.
-      sleep .2
-      echo "AUDIT:T:\${int_Task}:M" >> "\${dir_Failed}"/\${str_JobName}
+      echo "AUDIT:T:\${int_Task}:M" >> "\${file_Job}"
       (( int_Task+=1 ))
       echo "\$(${fn_LogDate}) +++Manual task - resume to continue. Resume point:\${int_Task}" >> "\${file_Log}"
       rm "\${LOCK}" 2>/dev/null
       exit 1
     fi
-    if [ \${b_Background} ] ; then
-      echo "FAILED Task \${int_Task} - But this is a subtask so this is never called"
-      set -x
-      lst_PID[\${int_Task}]="ERROR"
-      echo "failed task is lst_PID[\${int_Task}] : \${lst_PID[\${int_Task}]}"
-      echo "AUDIT:T:\${int_Task}:F" >> "\${dir_Running}"/\${str_JobName}
-      exit 1
-      set +x
-    else
-      echo "AUDIT:T:\${int_Task}:F" >> "\${dir_Running}"/\${str_JobName}
-      mv "\${dir_Running}"/\${str_JobName} "\${dir_Failed}"/.
-      sleep .2
-      echo "\$(${fn_LogDate}) +++Failed task \${int_Task}" >> "\${dir_Failed}"/\${str_JobName}
-      echo "\$(${fn_LogDate}) +++Failed task - skip or retry. Resume point:\${int_Task}" >> "\${file_Log}"
-      rm "\${LOCK}" 2>/dev/null
-      exit 1
-    fi
+    echo "AUDIT:T:\${int_Task}:F" >> "\${file_Job}"
+    mv "\${dir_Running}"/\${str_JobName} "\${dir_Failed}"/.
+    echo "\$(${fn_LogDate}) +++Failed task \${int_Task}" >> "\${file_Job}"
+    echo "\$(${fn_LogDate}) +++Failed task - skip or retry. Resume point:\${int_Task}" >> "\${file_Log}"
+    rm "\${LOCK}" 2>/dev/null
+    exit 1
   else
-    printf "\$(${fn_LogDate}) Completed task [\${int_Task}/\${int_Last}]\nAUDIT:T:\${int_Task}:C\n" >> "\${file_Log}"
-    echo "AUDIT:T:\${int_Task}:C" >> "\${dir_Running}"/\${str_JobName}
-    sleep .2
+    echo "AUDIT:T:\${int_Task}:C" >> "\${file_Job}"
+    printf "\$(${fn_LogDate}) Completed task [\${int_Task}/\${int_Last}]\n" >> "\${file_Log}"
   fi
   # Checking if PAUSED
   if [ -f "\${dir_Pause}"/\${str_JobName}".pause" ] ; then
@@ -141,12 +127,11 @@ fn_CheckTask()
       echo "\$(${fn_LogDate}) Last Task already. Cannot paused from task:\${int_Task}" >> "\${file_Log}"
       rm "\${dir_Pause}"/\${str_JobName}".pause"
     else
-      echo "AUDIT:T:\${int_Task}:P" >> "\${dir_Running}"/\${str_JobName}
-      sleep .2
+      echo "AUDIT:T:\${int_Task}:P" >> "\${file_Job}"
       mv "\${dir_Running}"/\${str_JobName} "\${dir_Failed}"/.
       rm "\${dir_Pause}"/\${str_JobName}".pause"
       (( int_Task+=1 ))
-      echo "\$(${fn_LogDate}) Paused. Automatically updated to Resume Point:\${int_Task}" >> "\${dir_Failed}"/\${str_JobName}
+      echo "\$(${fn_LogDate}) Paused. Automatically updated to Resume Point:\${int_Task}" >> "\${file_Job}"
       echo "\$(${fn_LogDate}) Paused. Automatically updated to Resume point:\${int_Task}" >> "\${file_Log}"
       rm "\${LOCK}" 2>/dev/null
       exit 1
@@ -166,7 +151,6 @@ fn_NiceTime()
 Manual()
 {
   printf "\n\n\t\$*\n\n"
-  #echo "Skip this task to continue."
   return 99
 }
 
@@ -178,37 +162,85 @@ Sleep()
 
 fn_ListTasksRemaining()
 {
-  local lst_Tasks=""
-  local lst_FailedTasks=""
-  local lst_SkipTasks=""
-  local int_Task=\$(grep AUDIT:T \${file_Log} | cut -d: -f3 | sort -un | tail -1)
-  local int_Count=0
-  local str_Mode=\${1:-}
+int_Count=0
+declare -A JOB
+while (( int_Count <= int_Last )) ; do
+  JOB[T\${int_Count}]=\$(grep "^AUDIT:T:\${int_Count}:" \${file_Job} | tail -1 | cut -d: -f4)
+  (( int_Count++ ))
+done
+
+#  if [[ "\${str_Mode}" == "skip" ]] ; then
+#    for each_FailedTask in \${lst_FailedTasks[*]} ; do
+#      grep -q "^AUDIT:T:\${int_Count}:[C|M|S|R]" \${file_Log} && lst_SkipTasks=(\${lst_SkipTasks[*]} \${each_FailedTask})
+#    done
+#    echo "Debug:Skipped: \${lst_SkipTasks[*]}"
+#    for each_SkipTask in \${lst_SkipTasks[*]} ; do
+#      echo "AUDIT:T:\${each_FailedTask}:S" #>> \${file_Log}
+#    done
+#  else
+#    echo "\${lst_Tasks[*]}"
+#  fi
+
+int_Count=0
+if [[ "\${str_Mode}" == "skip" ]] ; then
   while (( int_Count <= int_Last )) ; do
-    #echo "Debug:\$int_Count"
-    grep -q "^AUDIT:T:\${int_Count}:[C|M|S|R]" \${file_Log} || lst_Tasks=(\${lst_Tasks[*]} \${int_Count})
-    #grep  "^AUDIT:T:\${int_Count}:F" \${file_Log} && lst_FailedTasks=(\${lst_FailedTasks[*]} \${int_Count})
+    if [[ " " == "\$(echo \${JOB[T\${int_Count}]})" ]] ; then
+      echo \${int_Count}
+    else
+      echo "AUDIT:T:\${each_FailedTask}:S" >> "\${file_Job}"
+    fi
     (( int_Count++ ))
   done
-  #echo "Debug:Missed: \${lst_Tasks}"
-  #echo "Debug:Failed: \${lst_FailedTasks}"
-  if [[ "\${str_Mode}" == "skip" ]] ; then
-    for each_FailedTask in \${lst_FailedTasks[*]} ; do
-      grep -q "^AUDIT:T:\${int_Count}:[C|M|S|R]" \${file_Log} && lst_SkipTasks=(\${lst_SkipTasks[*]} \${each_FailedTask})
-    done
-    echo "Debug:Skipped: \${lst_SkipTasks[*]}"
-    for each_SkipTask in \${lst_SkipTasks[*]} ; do
-      echo "AUDIT:T:\${each_FailedTask}:S" #>> \${file_Log}
-    done
-
-  else
-    echo "\${lst_Tasks[*]}"
-  fi
-  # Check if its not already complete
-  #echo "AUDIT:T:\${each_FailedTask}:S" >> \${file_Log}
+else
+  while (( int_Count <= int_Last )) ; do
+    if [[ "F R" =~ "\$(echo \${JOB[T\${int_Count}]})" ]] ; then
+      echo \${int_Count}
+    fi
+    (( int_Count++ ))
+  done
+fi
 }
 
 EOF
+#  local lst_Tasks=""
+#  local lst_FailedTasks=""
+#  local lst_SkipTasks=""
+#  local int_Task=\$(grep AUDIT:T \${file_Log} | cut -d: -f3 | sort -un | tail -1)
+#  local int_Count=0
+#  local str_Mode=\${1:-}
+#  while (( int_Count <= int_Last )) ; do
+#    #echo "Debug:\$int_Count"
+#    grep -q "^AUDIT:T:\${int_Count}:[C|M|S|R]" \${file_Log} || lst_Tasks=(\${lst_Tasks[*]} \${int_Count})
+#    #grep  "^AUDIT:T:\${int_Count}:F" \${file_Log} && lst_FailedTasks=(\${lst_FailedTasks[*]} \${int_Count})
+#    (( int_Count++ ))
+#  done
+#  #echo "Debug:Missed: \${lst_Tasks}"
+#  #echo "Debug:Failed: \${lst_FailedTasks}"
+#  if [[ "\${str_Mode}" == "skip" ]] ; then
+#    for each_FailedTask in \${lst_FailedTasks[*]} ; do
+#      grep -q "^AUDIT:T:\${int_Count}:[C|M|S|R]" \${file_Log} && lst_SkipTasks=(\${lst_SkipTasks[*]} \${each_FailedTask})
+#    done
+#    echo "Debug:Skipped: \${lst_SkipTasks[*]}"
+#    for each_SkipTask in \${lst_SkipTasks[*]} ; do
+#      echo "AUDIT:T:\${each_FailedTask}:S" #>> \${file_Log}
+#    done
+#
+#  else
+#    echo "\${lst_Tasks[*]}"
+#  fi
+#  # Check if its not already complete
+#  #echo "AUDIT:T:\${each_FailedTask}:S" >> \${file_Log}
+#    if [ \${b_Background} ] ; then
+#      echo "FAILED Task \${int_Task} - But this is a subtask so this is never called"
+#      set -x
+#      lst_PID[\${int_Task}]="ERROR"
+#      echo "failed task is lst_PID[\${int_Task}] : \${lst_PID[\${int_Task}]}"
+#      echo "AUDIT:T:\${int_Task}:F" >> "\${dir_Running}"/\${str_JobName}
+#      exit 1
+#      set +x
+#    else
+#    fi
+
 }
 readonly -f fn_JobHeader
 
@@ -219,9 +251,9 @@ fn_JobFooter()
   ## The file to be appended to is passed as a variable
 
   typeset local file_Job="${1}"
-  #(( int_TaskCount-=1 ))
 
   ## echo "Adding footer to ${file_Job}"
+  (( int_TaskCount-- ))
   cat >> "${file_Job}" << EOF
 
 int_StartTask=\${int_ResumePoint:-0}
@@ -231,11 +263,11 @@ fn_ProcessTask()
 {
     local int_StartTask=\$1
     printf "===================\n" >> "\${file_Log}"
-    printf "\$(${fn_LogDate}) Starting task [\${int_StartTask}/\${int_Last}]\nAUDIT:T:\${int_StartTask}:R\n" >> "\${file_Log}"
+    printf "\$(${fn_LogDate}) Starting task [\${int_StartTask}/\${int_Last}]\n" >> "\${file_Log}"
     declare -f fn_Task_\${int_StartTask} | tail -n +3 | head -n -2 >> "\${file_Log}"
-    echo "AUDIT:T:\${int_StartTask}:R" >> "\${dir_Running}"/\${str_JobName}
-    sleep .2
+    echo "AUDIT:T:\${int_StartTask}:R" >> "\${dir_Active}"/\${str_JobName}
     fn_Task_\${int_StartTask}
+    sleep 1
 }
 
 if (( int_StartTask == 0 )) ; then
@@ -248,7 +280,7 @@ if (( int_StartTask == 0 )) ; then
 else
 
   # Idempotent processing
-  # echo "Processing \$(fn_ListTasksRemaining)"
+  echo "Idempotent Processing \$(fn_ListTasksRemaining)"
   for int_StartTask in \$(fn_ListTasksRemaining) ; do
     fn_ProcessTask \${int_StartTask}
   done
@@ -257,13 +289,13 @@ fi
 
 printf "===================\n" >> "\${file_Log}"
 
-printf "\$(${fn_LogDate}) Completed task:\${int_StartTask}\nAUDIT:T:\${int_StartTask}:C\n" >> "\${dir_Running}"/\${str_JobName}
+printf "\$(${fn_LogDate}) Completed task:\${int_StartTask}\nAUDIT:T:\${int_StartTask}:C\n" >> "\${dir_Active}"/\${str_JobName}
 mv "\${dir_Running}"/\${str_JobName} "\${dir_Completed}"/.
 rm "\${LOCK}" 2>/dev/null
 
-int_FailureCount=\$(egrep "[0-9]{6}-[0-9]{6}.+++Failed task" "\${dir_Completed}"/\${str_JobName} | wc -l)
-int_ManualCount=\$(egrep "[0-9]{6}-[0-9]{6}.+++Manual task" "\${dir_Completed}"/\${str_JobName} | wc -l)
-int_ManualCount=\$(egrep "^AUDIT:T:.*M$" "\${dir_Completed}"/\${str_JobName} | wc -l)
+int_FailureCount=\$(egrep "[0-9]{6}-[0-9]{6}.+++Failed task" "\${dir_Active}"/\${str_JobName} | wc -l)
+int_ManualCount=\$(egrep "[0-9]{6}-[0-9]{6}.+++Manual task" "\${dir_Active}"/\${str_JobName} | wc -l)
+int_ManualCount=\$(egrep "^AUDIT:T:.*M$" "\${dir_Active}"/\${str_JobName} | wc -l)
 echo "AUDIT:FINISH:\$(date "+%s")" >> "\${file_Log}"
 
 # CSV File
@@ -498,8 +530,7 @@ fn_PIDWait()
         lst_PIDResult="${lst_PIDResult}${int_Task}:0 "
         echo ">> SubTask ${int_Task} Output >>"
         cat ${file_Log}.${int_Task} 
-        printf "\\nAUDIT:T:${int_Task}:C\\n"
-        printf "\\nAUDIT:T:${int_Task}:C\\n" >> "${dir_Running}"/${str_JobName}
+        printf "\\nAUDIT:T:${int_Task}:C\\n" >> "${dir_Active}"/${str_JobName}
         echo "== End SubTask ${int_Task} Output ============"
       else
         int_PID_RC=$?
@@ -509,16 +540,16 @@ fn_PIDWait()
           lst_ManualTasks="${lst_ManualTasks}${int_Task} "
           cat ${file_Log}.${int_Task}           
           printf "\\nAUDIT:T:${int_Task}:M\\n"
-          echo "$(date +%%y%%m%%d-%%H%%M%%S) +++Manual task ${int_Task}" >> "${dir_Running}"/${str_JobName}
-          echo "AUDIT:T:${int_Task}:M" >> "${dir_Running}"/${str_JobName}
+          echo "$(date +%%y%%m%%d-%%H%%M%%S) +++Manual task ${int_Task}" >> "${dir_Active}"/${str_JobName}
+          echo "AUDIT:T:${int_Task}:M" >> "${dir_Active}"/${str_JobName}
         else
 
           lst_FailedTasks="${lst_FailedTasks}${int_Task} "
           echo ">> SubTask ${int_Task} FAILED ############"
           cat ${file_Log}.${int_Task} 
           printf "\\nAUDIT:T:${int_Task}:F\\n"
-          echo "$(date +%%y%%m%%d-%%H%%M%%S) +++Failed task ${int_Task}" >> "${dir_Running}"/${str_JobName}
-          echo "AUDIT:T:${int_Task}:F" >> "${dir_Running}"/${str_JobName}
+          echo "$(date +%%y%%m%%d-%%H%%M%%S) +++Failed task ${int_Task}" >> "${dir_Active}"/${str_JobName}
+          echo "AUDIT:T:${int_Task}:F" >> "${dir_Active}"/${str_JobName}
           echo "== End SubTask ${int_Task} Output ############"
           lst_PIDResult="${lst_PIDResult}${int_Task}:$int_PID_RC "
         fi
