#187 - Fixed set -e issue

diff --git a/obrar b/obrar
--- a/obrar
+++ b/obrar
@@ -65,10 +65,11 @@
 # 1.9 200529    marc        shellcheck start
 # 1.10 200613   marc        #146 Directory fixes for install
 # 1.11 221007   marc        shellcheck improvements and colour warn/error
+# 1.12 240108   marc        #187 Fixed -e option
 # shellcheck disable=SC2174
 
 # Program settings
-str_ProgramVersion="1.10"
+str_ProgramVersion="1.12"
 str_ProgramName="$(basename "$0")"
 str_FunctionName="${str_ProgramName}"
 dir_Run="$(dirname "$0")"
@@ -83,8 +84,7 @@ int_StartTime=$(date +%s)
 int_EndTime=0
 
 # Protect from undeclared variables
-set -u
-set -eio pipefail
+set -euo pipefail
 
 # User maintainable
 str_CommonBase=projects
@@ -138,11 +138,18 @@ Message()
     printf "$($cmd_LogDate) %15s FUNC  %s\n" "[${str_FunctionName}:${int_WarningCount}]" "$*"
   fi
 }
-Verbose() { [ "${b_Verbose}" ] && printf "$($cmd_LogDate) %15s \e[90mDEBUG\e[0m %s\n" "[${str_FunctionName}:${int_WarningCount}]" "$*" | tee -a ${file_Log};}
-Error()   {
+Verbose()
+{
+  if [ "${b_Verbose}" ] ; then
+    printf "$($cmd_LogDate) %15s \e[90mDEBUG\e[0m %s\n" "[${str_FunctionName}:${int_WarningCount}]" "$*" | tee -a ${file_Log}
+  fi
+}
+Error()
+{
   (( int_WarningCount=int_WarningCount + 1 ))
   printf "$($cmd_LogDate) %15s \e[31mERROR\e[0m ${SEPERATOR}\n" "[${str_FunctionName}:${int_WarningCount}]"
-  printf "$($cmd_LogDate) %15s \e[31mERROR\e[0m %s\n" "[${str_FunctionName}:${int_WarningCount}]" "$*"| tee -a ${file_Log};Verbose "Function chain: $(echo "${FUNCNAME[@]}"|tr -s " " "<")" | tee -a ${file_Log};   int_EndTime=$(date +%s) ; (( int_EndTime = int_EndTime - int_StartTime )) ; printf "$($cmd_LogDate) %15s \e[31mERROR\e[0m After %s seconds.\n" "[${str_FunctionName}:${int_WarningCount}]" "${int_EndTime}" | tee -a ${file_Log} ; exit 111;}
+  printf "$($cmd_LogDate) %15s \e[31mERROR\e[0m %s\n" "[${str_FunctionName}:${int_WarningCount}]" "$*"| tee -a ${file_Log};Verbose "Function chain: $(echo "${FUNCNAME[@]}"|tr -s " " "<")" | tee -a ${file_Log};   int_EndTime=$(date +%s) ; (( int_EndTime = int_EndTime - int_StartTime )) ; printf "$($cmd_LogDate) %15s \e[31mERROR\e[0m After %s seconds.\n" "[${str_FunctionName}:${int_WarningCount}]" "${int_EndTime}" | tee -a ${file_Log} ; exit 111
+}
 Warning() { (( int_WarningCount=int_WarningCount + 1 )); printf "$($cmd_LogDate) %15s \e[33mWARN\e[0m  %s\n" "[${str_FunctionName}:${int_WarningCount}]" "$*" | tee -a ${file_Log};}
 
 fn_GetJobID()
@@ -151,7 +158,7 @@ fn_GetJobID()
   # Function to create an atomic action of getting and recording a new job id
 
   file_JobID="${dir_Var}"/JobID.${str_ProgramName}
-  [[ ! -f "${file_JobID}" ]] && fn_CreateFile "${file_JobID}"
+  [[ ! -f "${file_JobID}" ]] && fn_CreateFile "${file_JobID}" || :
 
   declare file_JobIDLock="${file_JobID}".lock
   if ( set -o noclobber; true > "${file_JobIDLock}") 2> /dev/null ; then
@@ -181,7 +188,7 @@ fn_CreateFile()
     exit 1
   fi
   chmod 664 "${file_Name}" 2>/dev/null
-  [[ "${b_Blank}" ]] && true > "${file_Name}"
+  [[ "${b_Blank}" ]] && true > "${file_Name}" || :
   if [[ ! -z ${str_Group} ]] ; then
     Verbose "chgrp file '${file_Name}' with chgrp ${str_Group} " && sleep 2
     chgrp "${str_Group}" "${file_Name}" || echo "Error: Cannot chgrp ${str_Group} ${file_Name}. Check file and groups."
@@ -200,8 +207,8 @@ fn_Mkdir()
     Verbose "chgrp dir '${dir_Name}' with chgrp ${str_Group} " && sleep 2
     chgrp "${str_Group}" "${dir_Name}" || echo "Error: Cannot chgrp ${str_Group} ${dir_Name}. Check file and groups."
   else
-    :
     Verbose "Creating dir $dir_Name <${str_Group}>"
+    :
   fi
 }
 readonly -f fn_Mkdir
@@ -377,8 +384,12 @@ fn_CheckSetUp()
   Verbose "Making log directory mkdir -p -m 775 '${dir_LogBase}'"
   fn_Mkdir "${dir_LogBase}"
 
-  [[ -z ${file_TagDefinition} ]] && Error "No file_TagDefinition defined"
-  [[ -z ${str_Tag}     ]] && Error "No TAG passed"
+  if [[ -z ${file_TagDefinition} ]] ; then
+    Error "No file_TagDefinition defined"
+  fi
+  if [[ -z ${str_Tag}     ]] ; then
+    Error "No TAG passed"
+  fi
 }
 readonly -f fn_CheckSetUp
 
@@ -609,7 +620,11 @@ fn_ProcessFunctions()
 
     # Process Function
     str_Logging=
-    [[ ${b_Test} ]] && Message "TESTMODE: ${str_Function}" || ${str_Function} 2>&1 | tee -a ${file_Log}
+    if [[ ${b_Test} ]] ; then
+      Message "TESTMODE: ${str_Function}"
+    else
+      ${str_Function} 2>&1 | tee -a ${file_Log}
+    fi
     int_ReturnCode=${PIPESTATUS[0]}
     str_FunctionName=${str_ProgramName}
 
@@ -656,8 +671,8 @@ fn_UpdateTimings()
       (( int_Diff = int_CurrentAverage - int_Timing ))
       str_Diff="quicker"
     fi
-    (( int_Min > int_Timing )) && int_Min=${int_Timing}
-    (( int_Max < int_Timing )) && int_Max=${int_Timing}
+    (( int_Min > int_Timing )) && int_Min=${int_Timing} || :
+    (( int_Max < int_Timing )) && int_Max=${int_Timing} || :
     (( int_Average = int_CurrentAverage * int_Runs + int_Timing ))
     (( int_Runs++ ))
     (( int_Average = int_Average / int_Runs ))
@@ -712,7 +727,7 @@ Verbose "Sourcing common project etc files and functions"
 if [[ -r "${dir_Functions}" ]] ; then
   for file_CommonFunction in "${dir_Functions}/${str_FunctionIdentifier}"* ; do
     Verbose "  ${file_CommonFunction}"
-    ( bash "${dir_Functions}"/"${file_CommonFunction}" >/dev/null 2>&1 ) && source "${dir_Functions}"/"${file_CommonFunction}"
+    ( bash "${dir_Functions}"/"${file_CommonFunction}" >/dev/null 2>&1 ) && source "${dir_Functions}"/"${file_CommonFunction}" || :
   done
 else
   Warning "Cannot access common functions directory: ${dir_Functions}"
@@ -758,7 +773,10 @@ done
 Verbose "lst_TagArgs:${lst_TagArgs}"
 
 # If only asked to list the TAGs - only list the TAGs
-[ "${b_ListTags}" ] && fn_ListTags "${str_Tag}" && exit 0
+if [ "${b_ListTags}" ] ; then
+  fn_ListTags "${str_Tag}"
+  exit 0
+fi
 
 # If its not the TAGs, check everything it set up and process the request
 fn_CheckSetUp
