shellcheck updates

diff --git a/scorch b/scorch
--- a/scorch
+++ b/scorch
@@ -221,13 +221,15 @@
 ## 2.9.18 210426  marc   Adding Trim function to clean variables
 ## 2.10   210503  marc   Shellcheck for created jobs
 ## 2.11   210820  marc   Updates to typeset
+## 2.12   210830  marc   Shellcheck updates
 # shellcheck disable=SC2034
+# shellcheck disable=SC2154
 # shellcheck source=/dev/null
 ## Determine the program name and the running directory
 set -uo pipefail     # -e is not used yet as that is how plugins are loaded (or not loaded)
 IFS=$' \n\t'
 
-typeset str_ProgramVersion="2.11"
+typeset str_ProgramVersion="2.12"
 typeset       str_Codename="Fafnir"
 typeset  str_LatestVersion="check"
 typeset    str_ProgramName="$(basename "$0")"
@@ -601,17 +603,17 @@ if [[ ${file_Template} ]] ; then
         starting  ) echo "Running Own Jobs"                             ; fn_RunJobs ;;
         pending | running ) : ;;
         
-        failed    ) echo "$(basename ${file_Job}) FAILED"               ; exit 1 ;;
-        manual    ) echo "$(basename ${file_Job}) MANUAL STEP"          ; exit 99 ;;
-        completed ) echo "$(basename ${file_Job}) Completed"            ; exit 0 ;;
+        failed    ) echo "$(basename "${file_Job}") FAILED"               ; exit 1 ;;
+        manual    ) echo "$(basename "${file_Job}") MANUAL STEP"          ; exit 99 ;;
+        completed ) echo "$(basename "${file_Job}") Completed"            ; exit 0 ;;
         *         ) echo "What is ${str_JobState}"                      ; exit 1 ;;
       esac
       sleep 10
     done
 
     echo "Now find the jobs final resting place - completed or failed or lost"
-    find -L "${dir_Completed}" -name "$(basename ${file_Job})" && echo "SUCCESS" && exit 0
-    find -L "${dir_Failed}" -name "$(basename ${file_Job})" && echo "FAILED" && exit 1
+    find -L "${dir_Completed}" -name "$(basename "${file_Job}")" && echo "SUCCESS" && exit 0
+    find -L "${dir_Failed}" -name "$(basename "${file_Job}")" && echo "FAILED" && exit 1
 
     echo "waiting for ${str_JobName} to complete"
     set | grep SAFE
